Neos:
  Flow:
    mvc:
      routes:
        WebDevJona.ManyToManyTests: true
    persistence:
      backendOptions:
        dbname: 'dev'
        user: 'dev'
        password: 'dev'
        host: mysql
